# Generated by Django 5.0.6 on 2024-06-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condominio', models.CharField(choices=[('Condomínio A', 'Condomínio A'), ('Condomínio B', 'Condomínio B'), ('Condomínio C', 'Condomínio C')], max_length=100)),
                ('local', models.CharField(choices=[('andar1', 'Andar 1'), ('andar2', 'Andar 2'), ('andar3', 'Andar 3'), ('andar4', 'Andar 4'), ('andar5', 'Andar 5'), ('outrosAndares', 'Outros (especifique)'), ('unidade1', 'Unidade 1'), ('unidade2', 'Unidade 2'), ('unidade3', 'Unidade 3'), ('unidade4', 'Unidade 4'), ('unidade5', 'Unidade 5'), ('outrosUnidades', 'Outros (especifique)'), ('corredorPrincipal', 'Corredor Principal'), ('escadas', 'Escadas'), ('elevadores', 'Elevadores'), ('garagem', 'Garagem'), ('salaoFestas', 'Salão de Festas'), ('academia', 'Academia'), ('piscina', 'Piscina'), ('playground', 'Playground'), ('quadraEsportiva', 'Quadra Esportiva'), ('churrasqueira', 'Churrasqueira'), ('salaReunioes', 'Sala de Reuniões'), ('salaJogos', 'Sala de Jogos'), ('outrosAreasComuns', 'Outros (especifique)'), ('estacionamento', 'Estacionamento'), ('jardim', 'Jardim'), ('quadraTennis', 'Quadra de Tênis'), ('quadraFutebol', 'Quadra de Futebol'), ('patio', 'Pátio'), ('ciclovia', 'Ciclovia'), ('outrosExternos', 'Outros (especifique)'), ('outros', 'Outros (especifique)')], max_length=100)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('média', 'Média'), ('alta', 'Alta'), ('urgente', 'Urgente')], max_length=100)),
                ('categoria', models.CharField(choices=[('estrutural', 'Estrutural'), ('administrativo', 'Administrativo'), ('seguranca', 'Segurança'), ('emergencia', 'Emergência'), ('sinistro', 'Sinistro'), ('recursosHumanos', 'Recursos Humanos'), ('manutencaoRecorrente', 'Manutenção Recorrente')], max_length=100)),
                ('descricao', models.TextField()),
                ('foto', models.ImageField(upload_to='checklist_fotos/')),
                ('autor_tipo', models.CharField(max_length=100)),
                ('nome_autor', models.CharField(max_length=100)),
                ('cpf_autor', models.CharField(max_length=14)),
            ],
        ),
    ]
