# Generated by Django 5.0.6 on 2024-06-07 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='foto',
        ),
        migrations.AddField(
            model_name='checklist',
            name='uploads',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='fotos',
            field=models.ManyToManyField(blank=True, to='checklist.imagem'),
        ),
    ]
