# Generated by Django 5.0.6 on 2024-06-09 19:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0003_rename_descricao_checklist_descricao_problema_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklist',
            old_name='data_criacao',
            new_name='data_criacao_ocorrencia',
        ),
        migrations.AddField(
            model_name='checklist',
            name='data_criacao_upload',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
