# Generated by Django 5.0.6 on 2024-06-09 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0005_rename_data_criacao_ocorrencia_checklist_data_criacao_checklist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklist',
            old_name='data_criacao_checklist',
            new_name='data_checklist',
        ),
        migrations.RenameField(
            model_name='checklist',
            old_name='data_criacao_upload',
            new_name='data_upload',
        ),
    ]
