# Generated by Django 5.0.6 on 2024-06-23 22:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0006_rename_data_criacao_checklist_checklist_data_checklist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('concluido', 'Concluído'), ('em_andamento', 'Em andamento')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='data_checklist',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
