# Generated by Django 5.0.6 on 2024-06-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0007_checklist_status_alter_checklist_data_checklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='resolucao_problema',
            field=models.TextField(default='Resolução pendente'),
        ),
    ]
