# Generated by Django 5.0.6 on 2024-06-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0011_rename_imagem_checklist_upload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='resolucao_ocorrencia',
            field=models.TextField(blank=True, default='Resolução pendente', null=True),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='status',
            field=models.CharField(blank=True, choices=[('pendente', 'Pendente'), ('concluido', 'Concluído'), ('em_andamento', 'Em andamento')], default='pendente', max_length=20, null=True),
        ),
    ]
