# Generated by Django 5.0.6 on 2024-06-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_cadastrosindico_grupos_cadastrosindico_permissoes'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastrosindico',
            name='grupos',
        ),
        migrations.RemoveField(
            model_name='cadastrosindico',
            name='permissoes',
        ),
        migrations.AlterField(
            model_name='cadastrosindico',
            name='groups',
            field=models.ManyToManyField(related_name='cadastrosindico_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='cadastrosindico',
            name='user_permissions',
            field=models.ManyToManyField(related_name='cadastrosindico_permissions', to='auth.permission'),
        ),
    ]
