# Generated by Django 5.0.6 on 2024-06-05 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_cadastrosindico_grupos_and_more'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CadastroSindico',
            new_name='Cadastro_Sindico',
        ),
    ]
