# Generated by Django 5.0.6 on 2024-06-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_cadastrosindico_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastrosindico',
            name='last_login',
        ),
        migrations.AlterField(
            model_name='cadastrosindico',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
