# Generated by Django 5.0.6 on 2024-06-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_cadastrosindico_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrosindico',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
