# Generated by Django 5.0.6 on 2024-06-06 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_cadastrosindico_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastrosindico',
            name='is_superuser',
        ),
    ]
