# Generated by Django 5.0.6 on 2024-06-25 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_cadastrosindico_is_admin_cadastrosindico_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastrosindico',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='cadastrosindico',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='cadastrosindico',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='cadastrosindico',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
