# Generated by Django 5.0.6 on 2024-06-25 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_cadastrosindico_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastrosindico',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cadastrosindico',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cadastrosindico',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cadastrosindico',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cadastrosindico',
            name='fim_mandato',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cadastrosindico',
            name='inicio_mandato',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cadastrosindico',
            name='nome',
            field=models.CharField(blank=True, max_length=30, null=True),
  
        ),
    ]
    
